### ISSUE TITLE
Looking for someone to release packages for Homebrew and APT

### ISSUE THREAD

**Issue by jakewmeyer** [jakewmeyer/Geo#16]

**Comment by jakewmeyer** [comment]
Currently a package exists for Arch, looking for people willing to release on other platforms as well for flexible install options

**Comment by alexanderepstein** [comment]
Hey my repository [bash-snippets](https://github.com/alexanderepstein/Bash-Snippets) was actually added to [homebrew-core](https://github.com/Homebrew/homebrew-core/pull/16076) as of today. In the next few days I am going to update my repository and the formula to handle parameters so that the user can install specific tools. 

Something like ```brew install bash-snippets --only=geo```  (haven't decided on the name of the option yet).

**Comment by alexanderepstein** [comment]
As of todays formula you can run ```brew install bash-snippets --without-all-tools --with-geo``` and that will only install geo :tada:
